### ISSUE TITLE
React Feature Toggles Typings

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/frost-web#112]
Since @jwicks31 did all the work of providing typings for the library and most of the team has already worked on it, why not add the typings to the react-feature-toggle repo instead of here?

Adding typing declaration files to the repository that has the actual library is the standard way to handle this. It has the advantage that it won't affect regular JS users at all, but any TS users will benefit from it.

**Comment by kennylavender** [comment]
@jwicks31 can you create a pr? @geoffturk ping

**Comment by jwicks31** [comment]
I'm having a little trouble on figuring out where to include the file in react-feature-toggles. I've added the "types": "dist/index.d.ts" to the package.json and added the index.d.ts inside of the src folder. I'm not sure how to include the typescript file in the build though.

**Comment by kennylavender** [comment]
@jwicks31 checkout riteway or some of Eric's other projects, I think people have made PR's to add typings files to some of them, can't remember which ones at the moment.

**Comment by kennylavender** [comment]
Just my guess, but I think a type folder or file goes in the root folder, not the src or dist folder as there is no need for them to be compiled.

**Comment by jwicks31** [comment]
Ok I think I've got it. I tested it by downloading it into explorer-web with `npm install :[filepath]` and removed the declaration files from explorer-web. Everything worked doing it this way. I'll create the PR in react-feature-toggles. The file is saved in the root directory in a typings folder and in package.json it says: `"types": "typings/index.d.ts"`

**Comment by geoffturk** [comment]
@jwicks31 So this will be rft@2.0.0beta3?

**Comment by jwicks31** [comment]
@geoffturk Yes. It isn't published yet though. Still trying to figure out how to allow for currying with 3 arguments for one of the functions.

**Comment by geoffturk** [comment]
@jwicks31 I think we can close this one unless you are leaving it open until beta3 is published.
