### ISSUE TITLE
Verification email error message missing functional UI

### ISSUE THREAD

**Issue by ericelliott** [poetapp/frost-web#114]
## Actual Behavior

In production, attempting to verify my email, I was unable to. I didn't see any error messaging on screen, but got the following error in the console:

```
POST https://frost.po.et/api/accounts/verify 422 ()
```

![screen shot 2018-07-02 at 5 59 08 pm](https://user-images.githubusercontent.com/364727/42193399-21704840-7e23-11e8-8e42-230dc9b2d2ac.png)

Checking the network tab, I see that the reason for the error is an expired API token. After clicking "remove" and signing back in, I got a fresh token and was able to verify my email.

## Expected Behavior

If the token required to verify the user's email is expired, perhaps it would be better to automatically issue a fresh token and retry. That way, the user should have no need to see an error message or work out how to fix the problem themselves.

![screen shot 2018-07-02 at 6 10 28 pm](https://user-images.githubusercontent.com/364727/42193426-3a526a32-7e23-11e8-8a96-e6266717d980.png)

**Comment by geoffturk** [comment]
@jwicks31 Please have a look at this one once you have completed the first round of explorer-web work.
