### ISSUE TITLE
Netlify Issue

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/frost-web#122]
We are using `NODE_ENV` to indicate webpack whether the build was a production or testing build.
Netlify also uses the same environment variable to determine whether or not to install devDependencies.

When `NODE_ENV=production` Netlify skips installing devDependencies altogether.

This led to builds failing due to `webpack` being unavailable.

Retrying a build that failed due to `webpack` being unavailable without clearing cache would for god knows what reason actually build correctly, until now. 

See https://github.com/poetapp/explorer-web/pull/131

**Comment by geoffturk** [comment]
@lautarodragan It looks like the related PR has resolved this issue. I am closing it as a result.

**Comment by lautarodragan** [comment]
@geoffturk it has been merged to Jesse's branch, but not master. When do we consider an issue closed?

**Comment by geoffturk** [comment]
@lautarodragan Good point. I am not sure when that dangling branch is going to make it into master. Is it worth getting Jesse to slice out those changes into a separate PR that can be merged in directly ASAP?

**Comment by geoffturk** [comment]
@warrenv For you (or to reassign).
