### ISSUE TITLE
Implement new version of React router v4

### ISSUE THREAD

**Issue by wzalazar** [poetapp/frost-web#233]
We have a block to update the version of React router

![](https://user-images.githubusercontent.com/5795257/44993880-8b1f0a80-af72-11e8-8696-e9ebff9d3ba8.png)

**Comment by wolverinek14** [comment]
resolved with https://github.com/poetapp/frost-web/pull/232

**Comment by wzalazar** [comment]
resolved with https://github.com/poetapp/frost-web/pull/232
