### ISSUE TITLE
Fail on runtime

### ISSUE THREAD

**Issue by wzalazar** [poetapp/frost-web#245]
We need to set the functional tests, to prevent fails on runtime.
With this approach, we can avoid issues like this.

Updates the version of react-router

Update the version of `react-router`

![image](https://user-images.githubusercontent.com/5795257/45047194-bc6d0880-b04e-11e8-86ae-7964a959c906.png)

**Comment by wzalazar** [comment]
@geoffturk can you set the priority? Today the only test is checking the preview the Netlify

**Comment by geoffturk** [comment]
@wzalazar As discussed in Slack, let's deal with this after Mainnet.

**Comment by geoffturk** [comment]
@warrenv Please set overall priority for this in the testing epic we'll setup today.
