### ISSUE TITLE
Ensure development mode

### ISSUE THREAD

**Issue by wzalazar** [poetapp/frost-web#246]
We need to ensure the development mode on Travis. Sometimes a new dependency can break the environment of development.

issue related https://github.com/poetapp/frost-web/issues/240

**Comment by geoffturk** [comment]
@wzalazar Let's handle this one post Mainnet too unless you think it should be dealt with sooner. Let me know if you do.

**Comment by wzalazar** [comment]
@geoffturk yes, post Mainnet is good!!!

**Comment by geoffturk** [comment]
@jwicks31 Should we fold this into PNE or is this something we should deal with sooner?

**Comment by geoffturk** [comment]
@warrenv Testing epic...
