### ISSUE TITLE
Remove redirects and proxy

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/frost-web#292]
Now that Frost API supports CORS for all endpoints we should be able to get rid of the netlify redirects and the local dev proxy, which just add unnecessary complexity.

We'll need to replace them with a simple environment variable `FROST_API_URL` .

## Important

Since the new Frost API isn't deployed in production, implementing this change in Frost Web would break things. Will need to sync deployment.

**Comment by lautarodragan** [comment]
@geoffturk I'd implement this for mainnet-beta but it isn't critical - we can leave it in mainnet-launch and move it to mainnet-beta as we approach to completeness. 

Should be a small change.

**Comment by geoffturk** [comment]
I'm assigning to @wzalazar so he can work on it now. We can hide this behind a feature toggle so it does not affect production.

**Comment by lautarodragan** [comment]
Thanks!

Hiding this behind a feature toggle may be super hard though, since it happens at build time, not run time...

**Comment by geoffturk** [comment]
@jwicks31 Reassigning to you so you can pick this up in relation to: https://github.com/poetapp/random/issues/196
