### ISSUE TITLE
Tokens in Local Storage

### ISSUE THREAD

**Issue by kennylavender** [poetapp/frost-web#318]
https://www.rdegges.com/2018/please-stop-using-local-storage/

<img width="1221" alt="screen shot 2018-09-28 at 9 43 01 am" src="https://user-images.githubusercontent.com/5175120/46221697-fe623500-c302-11e8-9b90-c011ada410b9.png">

**Comment by kennylavender** [comment]
Thank you @wzalazar! Good points.

I believe storing the session information in our/a database instead of our application server solves your points on 'Sessions' and 'Scalability'.

We can use something like [koa-session-mongo](https://www.npmjs.com/package/koa-session-mongo) for this.

This is what @ericelliott  taught us to do instead of storing sessions on the application server. It allows scalability horizontally without the need for ugly things like sticky sessions.

**Comment by kennylavender** [comment]
As for CORS and CSRF, XSS, I don't have much understanding of those. Maybe I will make it one of my future Fridays to understand those better.

**Comment by kennylavender** [comment]
Edited above. I did not mean to apply that we should use normal stateful sessions.

**Comment by ericelliott** [comment]
What kind of token is that? If it's a session token that expires, it's probably fine. If it's a long-lived access token that basically grants the holder free reign to mess with your account at any time in the future, it's probably an issue. =)

**Comment by kennylavender** [comment]
It's the user apiTokens and the session token.

The session token is 24 hours.

I continued reading on this today, seems LocalStorage was chosen for simplicity and the less likely hood of XSS attacks since I don't think we have any external JS dependencies, so makes sense at this time for short lived sessions. 

Not sure if we want those apiTokens stored in localStorage though?

**Comment by geoffturk** [comment]
@wzalazar Can we wipe the API tokens from Local Storage when the user logs out? These are the bigger security risk vs. session tokens, and I can't think of any reason they should remain there after the user has closed his session.

**Comment by wzalazar** [comment]
@geoffturk with sessionStorage when the user closes the browser or tab the storage will clean. For example, If are log in a tab(session) and after that, you open another tab you must log in again.

**Comment by kennylavender** [comment]
The API key state doesn't need to be saved between refreshes and new page loads, does it? We can store the apiKeys in a separate reducer that does not get saved to local or session storage.
