### ISSUE TITLE
Incorrect Verify Email Link during local development testing

### ISSUE THREAD

**Issue by kennylavender** [poetapp/frost-web#331]
Confirm your email button link is broken.

It's missing the doamain and path.

Example:

```
http://?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imtlbm55LmxhdmVuZGVyQHBvLmV0IiwiY2xpZW50X3Rva2VuIjoiNER4QWhJSmJaMzUzc1JYc1lhc09JRGowIiwiaWF0IjoxNTM4NzA0Mzk5fQ.xD7sOasM04HWLeG1VwMJL0Ndzf2EmNY5utmMOQ3DX6k
```

**Comment by kennylavender** [comment]
This could have been due to not using containers for testing and development. It can be closed if that is the case. local-dev is now the required way of development https://github.com/poetapp/node/issues/523

**Comment by wzalazar** [comment]
@kennylavender you have to set this value in `Frost api`, we have these env vars

- `FROST_VERIFIED_ACCOUNT`
- `FROST_CHANGE_PASSWORD`

the values will depend of where you have `Frost-web`, for example:

```
  - FROST_VERIFIED_ACCOUNT=http://localhost:4000/verified-account
  - FROST_CHANGE_PASSWORD=http://localhost:4000/forgot-password/change-password

```

**Comment by warrenv** [comment]
Let's just focus on the `npm start` case right now and we can address `npm server` at another time if necessary.

So, something like:
const url = `http://localhost:${process.env.WEBPACK_PORT || 4000}/verified-account`

**Comment by wzalazar** [comment]
@kennylavender do you still consider an issue?

**Comment by kennylavender** [comment]
Thank you both.

@wzalazar I don't have time to test to see if local-dev works, local-dev is still not working correctly for me ( frost-web api requests are timing out, not connecting to frost-api ).

But if you guys are sure these settings are already provided correctly by default in local-dev containers then this can be closed.

**Comment by kennylavender** [comment]
Warren helped me get local-dev working. Tried to test this, but I am unable to get it to send me an email.

I tried turning both of these to false for frost-api, but I still didn't get an email.
```
  - VERIFIED_ACCOUNT=false
  - EMAIL_TRANSPORT_MAIL_DEV=false
```

**Comment by wzalazar** [comment]
@kennylavender should be 

- VERIFIED_ACCOUNT=false
 - EMAIL_TRANSPORT_MAIL_DEV=true

**Comment by kennylavender** [comment]
@wzalazar tried that combination as well. The email is still not being sent. Any other ideas?

**Comment by wzalazar** [comment]
can you paste your entire docker-compose config? you can get with this command for example:

```
docker-compose -f  docker-compose.yml config
```

**Comment by kennylavender** [comment]
Warren and I completely cleared out my containers and volumes. volumes were the cause of my previous issues.

**Comment by wzalazar** [comment]
sorry, it's working now?

**Comment by kennylavender** [comment]
no

**Comment by wzalazar** [comment]
always if you have doubts you can check the final result of the configuration for example, in my case I created another configuration

```
docker-compose -f docker-compose.yml -f docker-compose.development.yml config
```

**Comment by kennylavender** [comment]
Thanks, the overrides are working correctly from `docker-compose.overrides.yml`. Just no email being sent

**Comment by kennylavender** [comment]
We can get on a call tomorrow if that would be better?

**Comment by wzalazar** [comment]
ok, let me check tomorrow completely my `local-dev`

**Comment by jwicks31** [comment]
I started having this issue recently as well. 
Here are some things I've noticed.

With `VERIFIED_ACCOUNT=true` and `EMAIL_TRANSPORT_MAIL_DEV=true`: 
- If I use `npm run start` to start the app it will allow me to create an account, but won't redirect or send the email, instead it shows the error modal `This Account Already Exists`. I can then login with the same info, but it still shows the `Account Not Verified` banner and I'm unable to create/get works with the token.
- If I use `npm run start:ci` to start the app it will let me create the account and redirect, but the `Account Not Verified` banner still shows and I'm unable to create/get works. 

With `VERIFIED_ACCOUNT=true` and `EMAIL_TRANSPORT_MAIL_DEV=false`: 
- If I use `npm run start` to start the app it lets me create an account normally, but still shows the `Account Not Verified` banner. This time it did send the email to my actual email and I was able to use the link correctly. 
- If I use `npm run start:ci`to start the app it lets me create an account normally, but still shows the `Account Not Verified` banner. However, it does not send an email at all.

With `VERIFIED_ACCOUNT=false` and `EMAIL_TRANSPORT_MAIL_DEV=true`: 
- Same as `VERIFIED_ACCOUNT=true` and `EMAIL_TRANSPORT_MAIL_DEV=true`

With `VERIFIED_ACCOUNT=false` and `EMAIL_TRANSPORT_MAIL_DEV=false`:
- same as `VERIFIED_ACCOUNT=true` and `EMAIL_TRANSPORT_MAIL_DEV=false`:

**Comment by kennylavender** [comment]
Jesse, you may be getting `This Account Already Exists` because the volumes are being saved. Try using `docker-compose down --volumes` it deletes the volumes after removing the containers. Just learned that today from warren. If your already doing that, ignore this comment :)

**Comment by jwicks31** [comment]
I'm not using `docker-compose down --volumes` but I did stop/remove all the containers and prune the volumes between each test, so I'm fairly certain that isn't the case.

**Comment by wzalazar** [comment]
well, I found the issue. We're using this env var:

 - MAILDEV_PORT_25_TCP_ADDR=maildev
 - MAILDEV_PORT_25_TCP_PORT=25
but, this doesn't work because the method camelCaseToScreamingSnakeCase transform the words maildevPort25TcpPort and maildevPort25TcpAddr to MAILDEV_PORT25_TCP_ADDR MAILDEV_PORT25_TCP_PORT respectively

for this reason, we can take 2 ways to fix the problem

1 - Accept that behavior of camelCaseToScreamingSnakeCase is correct. If we take this way we have to use:

 - MAILDEV_PORT25_TCP_ADDR=maildev
 - MAILDEV_PORT25_TCP_PORT=25
2 - Change the behavior of camelCaseToScreamingSnakeCase


@kennylavender @jwicks31 @warrenv @lautarodragan

**Comment by warrenv** [comment]
How about dropping the '_25_' from the variable names?

**Comment by wzalazar** [comment]
@warrenv yes, it's another possibility

**Comment by kennylavender** [comment]
Nice work debugging @wzalazar 👍 

@wzalazar @warrenv I am good with dropping the '25' from the name if that is simple enough and @WesleyCharlesBlake is good with updating it anywhere it needs to be updated.

**Comment by wzalazar** [comment]
awesome, I'm good with dropping the '25' also

**Comment by WesleyCharlesBlake** [comment]
I'm happy to remove the `25`
