### ISSUE TITLE
Unable to copy token from web UI in iOS 11 (Safari)

### ISSUE THREAD

**Issue by bisbell** [poetapp/frost-web#39]
When viewing https://frost.po.et/token on an Apple device (iPhone, iPad) iOS 11 (Safari), you are not able to copy the API token from the UI.

A single-click to copy (which executes the following code), fails to copy the token to the clipboard.
[https://github.com/poetapp/frost-web/blob/ca09a3903d71a68a7feaa36a4b6a0a11784f4411/src/components/atoms/CopyableText/CopyableText.tsx#L68-L69](https://github.com/poetapp/frost-web/blob/ca09a3903d71a68a7feaa36a4b6a0a11784f4411/src/components/atoms/CopyableText/CopyableText.tsx#L68-L69)

And press-and-hold to bring up the browser's native 'copy' menu only allows you to copy the abbreviated token that is displayed on screen (which is not a valid token). The abbreviated token that is copied to the clipboard includes the '...' E.g. 123456789...abcdefghij

A current workaround is to use a desktop browser to copy the token and email the full token to myself. Then I can copy/paste from the email to get the token on a iOS device.

Fix may include making accomodations for the onclick function to work in iOS 11 (Safari) or showing the full API token when on iOS so that user can use native press-and-hold copy to get the token.

**Comment by geoffturk** [comment]
@bisbell Can you confirm if this has resolved the issue for you too?

**Comment by bisbell** [comment]
@geoffturk , thanks Geoff. Copy/paste token now works for me on iOS mobile Safari (on the new site - explorer.poetnetwork.net)

Though I'm running into a few separate issues now on mobile, I will log them separately when I can consistently reproduce and document. Thanks.
