### ISSUE TITLE
frost.po.et/token gives client script errors

### ISSUE THREAD

**Issue by damianof** [poetapp/frost-web#45]
Tried from latest Chrome:

<details>
<summary>
<code>app.93a3b335ab3263aac5c7.js:8159 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined</code>
</summary>
<pre><code>
    at exports.BoxToken.props (app.93a3b335ab3263aac5c7.js:8159)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (vendor.js:14235)
    at ReactCompositeComponentWrapper._constructComponent (vendor.js:14211)
    at ReactCompositeComponentWrapper.mountComponent (vendor.js:14114)
    at Object.mountComponent (vendor.js:7011)
    at ReactDOMComponent.mountChildren (vendor.js:13144)
    at ReactDOMComponent._createInitialChildren (vendor.js:10237)
    at ReactDOMComponent.mountComponent (vendor.js:10056)
    at Object.mountComponent (vendor.js:7011)
    at ReactCompositeComponentWrapper.performInitialMount (vendor.js:14297)
exports.BoxToken.props @ app.93a3b335ab3263aac5c7.js:8159
_constructComponentWithoutOwner @ vendor.js:14235
_constructComponent @ vendor.js:14211
mountComponent @ vendor.js:14114
mountComponent @ vendor.js:7011
mountChildren @ vendor.js:13144
_createInitialChildren @ vendor.js:10237
mountComponent @ vendor.js:10056
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
mountChildren @ vendor.js:13144
_createInitialChildren @ vendor.js:10237
mountComponent @ vendor.js:10056
mountComponent @ vendor.js:7011
mountChildren @ vendor.js:13144
_createInitialChildren @ vendor.js:10237
mountComponent @ vendor.js:10056
mountComponent @ vendor.js:7011
mountChildren @ vendor.js:13144
_createInitialChildren @ vendor.js:10237
mountComponent @ vendor.js:10056
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
mountChildren @ vendor.js:13144
_createInitialChildren @ vendor.js:10237
mountComponent @ vendor.js:10056
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
mountChildren @ vendor.js:13144
_createInitialChildren @ vendor.js:10237
mountComponent @ vendor.js:10056
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
mountChildren @ vendor.js:13144
_createInitialChildren @ vendor.js:10237
mountComponent @ vendor.js:10056
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
performInitialMount @ vendor.js:14297
mountComponent @ vendor.js:14184
mountComponent @ vendor.js:7011
mountComponentIntoNode @ vendor.js:19451
perform @ vendor.js:7489
batchedMountComponentIntoNode @ vendor.js:19473
perform @ vendor.js:7489
batchedUpdates @ vendor.js:17022
batchedUpdates @ vendor.js:6665
_renderNewRootComponent @ vendor.js:19666
_renderSubtreeIntoContainer @ vendor.js:19748
render @ vendor.js:19769
(anonymous) @ app.93a3b335ab3263aac5c7.js:121
fulfilled @ app.93a3b335ab3263aac5c7.js:64
Promise.then (async)
step @ app.93a3b335ab3263aac5c7.js:79
(anonymous) @ app.93a3b335ab3263aac5c7.js:81
__awaiter @ app.93a3b335ab3263aac5c7.js:61
init @ app.93a3b335ab3263aac5c7.js:93
Object.defineProperty.value @ app.93a3b335ab3263aac5c7.js:124
__webpack_require__ @ meta.js:74
Object.defineProperty.value @ app.93a3b335ab3263aac5c7.js:6
__webpack_require__ @ meta.js:74
webpackJsonpCallback @ meta.js:45
(anonymous) @ app.93a3b335ab3263aac5c7.js:1
2vendor.js:3797 Uncaught TypeError: Cannot read property '__reactInternalInstance$tsfzw4of6w' of null
    at Object.getClosestInstanceFromNode (vendor.js:3797)
    at findParent (vendor.js:17068)
    at handleTopLevelImpl (vendor.js:17097)
    at ReactDefaultBatchingStrategyTransaction.perform (vendor.js:7489)
    at Object.batchedUpdates (vendor.js:17022)
    at Object.batchedUpdates (vendor.js:6665)
    at dispatchEvent (vendor.js:17177)
</code></pre>
</details>

**Comment by wzalazar** [comment]
Hi @damianof, I appreciate your report. 

Could you tell me step by step to reproduce this issue?

**Comment by damianof** [comment]
Hey @wzalazar sorry for the delay. I solved the problem by logging into a new session with incognito window in Chrome, so I guess it might have to do with outdated cookies. Here is a screen shot of the error when i tried for example to delete one of the older tokens. (but again, I am good now logging through incognito window it works) https://www.screencast.com/t/x3sdZAgG

**Comment by lautarodragan** [comment]
Thanks a lot @damianof for the thorough report! 

I believe this issue is related to #47 and #59.

**Comment by jwicks31** [comment]
Is this issue resolved with #91?

**Comment by wzalazar** [comment]
@jwicks31 in this issue report we have two issues

1.  was solved with this PR, #57
2. two  #91

therefore, we can close this issue ticket
