### ISSUE TITLE
Login button blocked on small screen by "Forgot your password?"

### ISSUE THREAD

**Issue by bisbell** [poetapp/frost-web#503]
On the page https://explorer.poetnetwork.net/login , in the "Already Signed Up?" section, the Login button is blocked by the "Forgot you password?" link on a small screen in portrait mode (e.g. iPhone X Safari portrait layout). See screenshot below:

![img_2066](https://user-images.githubusercontent.com/2301316/49348200-bc8a9d80-f669-11e8-8b52-d53f6d03f0df.PNG)

The login button is almost impossible to click with this overlap.

I am able to rotate my phone to landscape and it does layout in a way where I can click the login button. But this workaround may not be apparent or work on all screen sizes. Here is the screenshot in landscape layout.

![img_2067](https://user-images.githubusercontent.com/2301316/49348199-b5fc2600-f669-11e8-87fd-485745e04cb1.PNG)

**Comment by lautarodragan** [comment]
Thank you @bisbell for the thorough bug report!
