### ISSUE TITLE
Fix broken image links & date in confirmation email

### ISSUE THREAD

**Issue by geoffturk** [poetapp/frost-web#88]
The three images at the bottom of the confirmation email are all broken.

Also, the copyright year needs to be updated. Let's use some JS like `(new Date()).getFullYear()` so it is future-proof.

![confirmation-email](https://user-images.githubusercontent.com/32190662/40472644-538ede8e-5f3a-11e8-8a5c-e0961345c155.png)

**Comment by jwicks31** [comment]
I recreated the issue in frost-api.
