### ISSUE TITLE
Could not create the workroot

### ISSUE THREAD

**Issue by ar-anvd** [poetapp/frost-web#95]
I am using the exact info in [docs](https://docs.frost.po.et/docs/getting-started), but I am getting: **Could not create the work**

As far as I can see in API docs, it means an error [400](https://docs.frost.po.et/reference#create-work) 

Last week, everything worked fine for me 

```
curl -H "Content-Type: application/json" -H "token: $FROST_TOKEN" -X POST -d '{"name":"Hello World", "datePublished":"2018-02-06T14:39:46+00:00", "dateCreated": "2018-02-06T14:39:46+00:00","author": "Jameson", "tags": "test", "content": "Hello, World!"}' $FROST_URL/works
```

**Comment by lautarodragan** [comment]
Thanks @ar-anvd for the report!

I believe we've fixed this now. Can you try again please?

**Comment by ar-anvd** [comment]
@lautarodragan Yes, it works correctly now.  Can I ask a question about testnet? When Livenet became available, it will have some migration of data?
